Implemented multiple changes.
* implement nprogress

* make a new page.

/setup/organization
/setup/administrativeArea
/setup/t

* Try fixing this error: `Runtime Error: TypeError: Super expression must

* update the page from /agriculture-livestock to /agriculture
and then del

* make the 404 page now

* ✅ Fix: Make the page or the chart a Client Component
Option A — Make the

* Runtime Error

TypeError: Super expression must either be null or a fun

* Try fixing this error: `Runtime Error: Error: useChart must be used with

* make the following page:

/setup/
/setup/organization
/setup/location
/s

* Set up a Firebase backend

* the theme should be something simple, and elegant and minimal.
the conte

* the sidebar keep that too inside the 1440px width.
that should be inside

* add /setup and other pages in the sidebar.

* /setup show items on that page like the image provided, not cards multip

* make the following pages:

/setup/organization/create
/setup/organizatio

* make the following databases.
-> region
-> organization

and then connec

* on the firebase rules, allow everything for the next 15 days, it's being

* never use use collection for any database operations like reading as wel

* implement nprogress

* make a new page.
/entry

and make these pages as well.
/entry/citizen
->

* firebase rules time, set the time to 2027. it;s to be released on march

* FirebaseError: Function addDoc() called with invalid data. Unsupported f

* in the current location and permanent location, show from the regions.

* /citizen-registry
change this to:
/citizens

* /citizen-registry change this to: /citizens

then delete
/citizen-regist

* in the /citizens page show real data from the database.

* /entry/death
/entry/education
/entry/occupation

make these pages.
in de

* /infrastructure-resources
change this page to
/infrastructure

and make

* Births (This Year)
Deaths (This Year)

show this data by real data from

* in the occupation page, allow passing the expected monthly income of the

* on the homepage, show total population from the database.
then show aver

* in the homepage, show a male to female ratio.
on the homepage. then chil

* on the /citizens page
by clicking on citizen name, take the user to /cit

* make the page

/entry/residency

ask for previous residency
then ask for

* in the homepage, instead of population growth, add a age distribution gr

* employment rate should be counted with the following method:

citizen wi

* if employment condition has not been set, it means unemployed

* in the /residency-migration
change the page url to
/residency

delete th

* the migration charge is like fake data, show that from the database.

* update the permanent residency data. it's still sample data

* in the internal migration and international migration, show na

* change page names.
frrom data entry to entry

citizens registry to citiz

---------

Co-authored-by: Kishor Neupane <rolpamunicipality.clients@neupgroup.com>